name: validate

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  repository-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - shell: pwsh
        run: ./tools/validate.ps1
